[package]
name = "strenc"
version = "0.1.1"
edition = "2018"
authors = ["FssAy"]
license = "Apache-2.0"

[lib]
path = "src/strenc.rs"
proc-macro = true

[dependencies]
magic-crypt = "3.1.8"
quote = "1.0.9"
proc-macro2 = "1.0.27"
random-string = "0.2.0"
